### ISSUE TITLE
Any plans for a pre-built docker image?

### ISSUE THREAD

**Issue by ovizii** [alex-swki/magicpack#1]
I would love to have a ready image published say on docker hub, so I can use it with a compose file without having to clone this registry, keep it updated and having to build my own image.

**Comment by alex-swki** [comment]
Yes I will make a prebuilt image this week. Thank you for your suggestion. You will be hearing from me when thats done

**Comment by alex-swki** [comment]
Hey, sorry for the delay. I just created the prebuilt image. See the Readme for more info on deployment with the prebuilt image.
Thank you again for your suggestion!
